"""CI/CD scaffolding: generate GitHub Actions workflow files."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

_WORKFLOW_TEMPLATE = """\
# Auto-generated by: bananarama ci init
# Runs bananarama on push to main and PRs that touch YAML files.
# - PRs: dry-run only (cost estimate, no API calls)
# - Push to main: actual generation + artifact upload

name: Bananarama Generate

on:
  push:
    branches: [main]
    paths: ['**/*.yaml', '**/*.yml']
  pull_request:
    paths: ['**/*.yaml', '**/*.yml']

jobs:
  generate:
    uses: bfraca/bananaramapy/.github/workflows/generate.yaml@main
    with:
      config: {config}
      dry-run: ${{{{ github.event_name == 'pull_request' }}}}
      concurrency: {concurrency}{max_cost_line}{extra_deps_line}
    secrets:
      GEMINI_API_KEY: ${{{{ secrets.GEMINI_API_KEY }}}}
      OPENAI_API_KEY: ${{{{ secrets.OPENAI_API_KEY }}}}
      TOGETHER_API_KEY: ${{{{ secrets.TOGETHER_API_KEY }}}}
"""


def scaffold_workflow(
    dest_dir: Path,
    *,
    config: str = "bananarama.yaml",
    concurrency: int = 5,
    max_cost: float | None = None,
    extra_deps: str = "",
    overwrite: bool = False,
) -> Path:
    """Generate a GitHub Actions workflow file for bananarama.

    Args:
        dest_dir: Root of the target repository.
        config: Path to the bananarama YAML config (relative to repo root).
        concurrency: Max concurrent API calls.
        max_cost: Optional cost threshold in USD.
        extra_deps: Optional extras to install (e.g. "all", "openai").
        overwrite: If True, overwrite an existing workflow file.

    Returns:
        Path to the created workflow file.

    Raises:
        FileExistsError: If workflow already exists and overwrite is False.
    """
    workflow_dir = dest_dir / ".github" / "workflows"
    workflow_file = workflow_dir / "bananarama.yaml"

    if workflow_file.exists() and not overwrite:
        msg = f"'{workflow_file}' already exists. Use --overwrite to replace it."
        raise FileExistsError(msg)

    max_cost_line = ""
    if max_cost is not None:
        max_cost_line = f"\n      max-cost: {max_cost}"

    extra_deps_line = ""
    if extra_deps:
        extra_deps_line = f"\n      extra-deps: {extra_deps}"

    content = _WORKFLOW_TEMPLATE.format(
        config=config,
        concurrency=concurrency,
        max_cost_line=max_cost_line,
        extra_deps_line=extra_deps_line,
    )

    workflow_dir.mkdir(parents=True, exist_ok=True)
    workflow_file.write_text(content)
    return workflow_file
